"""add length column

Revision ID: 5f2166b52b4f
Revises: 3d8628dd9707
Create Date: 2023-09-07 19:51:25.824900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2166b52b4f'
down_revision = '3d8628dd9707'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'length')
    # ### end Alembic commands ###
